class Sequence():

    def sequence_1(self):
        dictionary = {"sequence_1": {"step_1": [{"id": 0,
                                                 "pos": 0},
                                                {"id": 1,
                                                 "pos": 0},
                                                {"id": 2,
                                                 "pos": 0},
                                                {"id": 3,
                                                 "pos": 0},
                                                {"id": 4,
                                                 "pos": 0},
                                                {"id": 5,
                                                 "pos": 0}
                                                ],
                                     "step_2": [{"id": 0,
                                                 "pos": 1000},
                                                {"id": 1,
                                                 "pos": 350},
                                                {"id": 5,
                                                 "pos": 620},
                                                {"id": 2,
                                                 "pos": -590},
                                                {"id": 1,
                                                 "pos": 530},
                                                {"id": 5,
                                                 "pos": 23}
                                                ],

                                     "step_3": [{"id": 1,
                                                 "pos": 0},
                                                {"id": 2,
                                                 "pos": -310},
                                                {"id": 3,
                                                 "pos": 230},
                                                {"id": 4,
                                                 "pos": 1000},
                                                {"id": 0,
                                                 "pos": -570},
                                                {"id": 2,
                                                 "pos": -590},
                                                {"id": 3,
                                                 "pos": 0},
                                                {"id": 1,
                                                 "pos": 500},
                                                {"id": 5,
                                                 "pos": 620}
                                                ],
                                     "step_4": [{"id": 1,
                                                 "pos": 0},
                                                {"id": 2,
                                                 "pos": 0},
                                                {"id": 0,
                                                 "pos": 0},
                                                {"id": 3,
                                                 "pos": 0},
                                                {"id": 4,
                                                 "pos": 0},
                                                {"id": 5,
                                                 "pos": 0}
                                                ]}}

        return dictionary
